baseURL = 'http://epistemology.dev/'
languageCode = 'en-us'
title = 'Software Developer Epistemology'
publishDir = "docs"
theme = "holy"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true